# cl model
model: adam

# experimental args
lr: 0.0001
weight_decay: 0.00001
n_epochs: 150
batch_size: 10
gpus: [0,1]
num_workers: 16

# backbone args
feature_extractor: backbone.I3D_backbone.I3D_backbone
feature_extractor_args:
  I3D_class: 400
  I3D_ckpt_path: ./weights/model_rgb.pth

projector: backbone.Projector.Projector
projector_args:
  in_channels: 1024

regressor: backbone.DAE.DAE
regressor_args:
  in_channels: 1024
  out_channels: 1

# dataset setting
dataset: class-mtl
dataset_args:
  data_root: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA/new
  label_path: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA/info/final_annotations_dict_with_dive_number.pkl
  train_split: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA/info/train_split_0.pkl
  test_split: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA/info/test_split_0.pkl
  frame_length: 103
  temporal_shift: [-3, 3]
  usingDD: False

#weight_path: ./outputs/domain-mtl/adam05/weights/last.pth

